# Generated by Django 6.0.5 on 2026-06-21 02:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dietetic", "0006_remove_paciente_full_name_paciente_first_name_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CategoriaAlimento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Categorias Alimento",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="alimentoprogramado",
            name="categoria_alimento",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="alimentos_programados",
                to="dietetic.categoriaalimento",
            ),
        ),
        migrations.CreateModel(
            name="DiaPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_dia", models.CharField(max_length=100)),
                ("orden", models.PositiveIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "plan_nutricional",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dias_plan",
                        to="dietetic.plannutricional",
                    ),
                ),
            ],
            options={
                "ordering": ["orden"],
                "unique_together": {("plan_nutricional", "orden")},
            },
        ),
        migrations.CreateModel(
            name="EvaluacionAntropometrica",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("peso", models.DecimalField(decimal_places=2, max_digits=6)),
                ("altura", models.DecimalField(decimal_places=2, max_digits=6)),
                (
                    "imc",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "grasa_corporal_porcentaje",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "masa_muscular_kg",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "consulta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evaluaciones_antropometricas",
                        to="dietetic.consultadietetica",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FacturaPago",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("monto", models.DecimalField(decimal_places=2, max_digits=10)),
                ("fecha_pago", models.DateTimeField(blank=True, null=True)),
                (
                    "estado_pago",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente"),
                            ("pagado", "Pagado"),
                            ("anulado", "Anulado"),
                        ],
                        default="pendiente",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "consulta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="facturas_pago",
                        to="dietetic.consultadietetica",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="HistorialClinico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("alergias", models.TextField(blank=True, default="")),
                ("enfermedades_cronicas", models.TextField(blank=True, default="")),
                ("antecedentes_familiares", models.TextField(blank=True, default="")),
                ("medicamentos_actuales", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "paciente",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historial_clinico",
                        to="dietetic.paciente",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MensajeChat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("contenido", models.TextField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("leido", models.BooleanField(default=False)),
                (
                    "destinatario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mensajes_recibidos",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "remitente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mensajes_enviados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="MomentoComida",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_momento", models.CharField(max_length=100)),
                ("orden", models.PositiveIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "dia_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="momentos_comida",
                        to="dietetic.diaplan",
                    ),
                ),
            ],
            options={
                "ordering": ["orden"],
                "unique_together": {("dia_plan", "orden")},
            },
        ),
        migrations.CreateModel(
            name="NotaConsulta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("diagnostico", models.TextField(blank=True, default="")),
                ("observaciones", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "consulta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notas_consulta",
                        to="dietetic.consultadietetica",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="NotificacionPush",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("mensaje", models.TextField()),
                ("leido", models.BooleanField(default=False)),
                ("fecha_envio", models.DateTimeField(auto_now_add=True)),
                (
                    "paciente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notificaciones_push",
                        to="dietetic.paciente",
                    ),
                ),
            ],
            options={
                "ordering": ["-fecha_envio"],
            },
        ),
        migrations.CreateModel(
            name="ProgresoFoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("foto", models.ImageField(upload_to="progresos_fotos/")),
                ("descripcion", models.TextField(blank=True, default="")),
                ("fecha_subida", models.DateTimeField(auto_now_add=True)),
                (
                    "paciente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progresos_fotos",
                        to="dietetic.paciente",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Progresos Fotos",
                "ordering": ["-fecha_subida"],
            },
        ),
        migrations.CreateModel(
            name="RegistroAgua",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateField()),
                ("cantidad_ml", models.PositiveIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "paciente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registros_agua",
                        to="dietetic.paciente",
                    ),
                ),
            ],
            options={
                "ordering": ["-fecha"],
            },
        ),
        migrations.CreateModel(
            name="RutinaEjercicio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descripcion_rutina", models.TextField()),
                ("dias_semana", models.CharField(max_length=100)),
                ("duracion_minutos", models.PositiveIntegerField(default=30)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "plan_nutricional",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rutinas_ejercicio",
                        to="dietetic.plannutricional",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DetallePlanAlimento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cantidad_gramos",
                    models.DecimalField(decimal_places=2, max_digits=7),
                ),
                ("orden", models.PositiveIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "alimento_programado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detalles_plan",
                        to="dietetic.alimentoprogramado",
                    ),
                ),
                (
                    "momento_comida",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detalles_alimentos",
                        to="dietetic.momentocomida",
                    ),
                ),
            ],
            options={
                "ordering": ["orden"],
                "unique_together": {("momento_comida", "alimento_programado")},
            },
        ),
        migrations.CreateModel(
            name="SeguimientoConsumo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateField()),
                ("completado", models.BooleanField(default=False)),
                ("notas", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "momento_comida",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seguimientos_consumo",
                        to="dietetic.momentocomida",
                    ),
                ),
                (
                    "paciente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seguimientos_consumo",
                        to="dietetic.paciente",
                    ),
                ),
            ],
            options={
                "ordering": ["-fecha"],
                "unique_together": {("paciente", "momento_comida", "fecha")},
            },
        ),
    ]
