# Generated by Django 6.0.5 on 2026-06-23 13:07

import dietetic.models.user_profile
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dietetic", "0007_categoriaalimento_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("ADMIN", "Administrador"),
                            ("NUTRICIONISTA", "Nutricionista"),
                            ("PACIENTE", "Paciente"),
                        ],
                        default="PACIENTE",
                        max_length=20,
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=dietetic.models.user_profile.user_avatar_path,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="HorarioNutricionista",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dia_semana",
                    models.CharField(
                        choices=[
                            ("LUN", "Lunes"),
                            ("MAR", "Martes"),
                            ("MIE", "Miércoles"),
                            ("JUE", "Jueves"),
                            ("VIE", "Viernes"),
                            ("SAB", "Sábado"),
                            ("DOM", "Domingo"),
                        ],
                        max_length=3,
                    ),
                ),
                ("hora_inicio", models.TimeField()),
                ("hora_fin", models.TimeField()),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "nutricionista",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="horarios",
                        to="dietetic.nutricionista",
                    ),
                ),
            ],
            options={
                "ordering": ["dia_semana", "hora_inicio"],
                "unique_together": {("nutricionista", "dia_semana", "hora_inicio")},
            },
        ),
        migrations.CreateModel(
            name="RegistroEjercicio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateField()),
                ("completado", models.BooleanField(default=False)),
                ("notas", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "paciente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registros_ejercicio",
                        to="dietetic.paciente",
                    ),
                ),
                (
                    "rutina_ejercicio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registros",
                        to="dietetic.rutinaejercicio",
                    ),
                ),
            ],
            options={
                "ordering": ["-fecha"],
                "unique_together": {("paciente", "rutina_ejercicio", "fecha")},
            },
        ),
        migrations.CreateModel(
            name="SintomaDiario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateField()),
                (
                    "sintoma",
                    models.CharField(
                        choices=[
                            ("ANSIEDAD", "Ansiedad"),
                            ("CANSANCIO", "Cansancio"),
                            ("DOLOR_CABEZA", "Dolor de cabeza"),
                            ("BUENA_ENERGIA", "Buena energía"),
                            ("HAMBRE_EXCESIVA", "Hambre excesiva"),
                            ("SUEÑO_MALO", "Mal sueño"),
                            ("SUEÑO_BUENO", "Buen sueño"),
                        ],
                        max_length=20,
                    ),
                ),
                ("notas", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "paciente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sintomas_diarios",
                        to="dietetic.paciente",
                    ),
                ),
            ],
            options={
                "ordering": ["-fecha"],
                "unique_together": {("paciente", "fecha")},
            },
        ),
    ]
