# Generated by Django 6.0.6 on 2026-06-25 00:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "dietetic",
            "0008_userprofile_horarionutricionista_registroejercicio_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="LogroPaciente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=200)),
                ("descripcion", models.TextField(blank=True, default="")),
                ("fecha_logro", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "paciente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logros",
                        to="dietetic.paciente",
                    ),
                ),
            ],
            options={
                "ordering": ["-fecha_logro"],
            },
        ),
        migrations.CreateModel(
            name="ObjetivoPaciente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "objetivo",
                    models.CharField(
                        choices=[
                            ("BAJAR_PESO", "Bajar peso"),
                            ("GANAR_MASA", "Ganar masa muscular"),
                            ("MANTENER_PESO", "Mantener peso"),
                            ("REDUCIR_GRASA", "Reducir grasa corporal"),
                            ("MEJORAR_SALUD", "Mejorar salud general"),
                            ("MEJORAR_RENDIMIENTO", "Mejorar rendimiento deportivo"),
                            ("OTRO", "Otro"),
                        ],
                        max_length=30,
                    ),
                ),
                ("fecha_inicio", models.DateField()),
                ("fecha_meta", models.DateField(blank=True, null=True)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("PENDIENTE", "Pendiente"),
                            ("EN_PROGRESO", "En progreso"),
                            ("CUMPLIDO", "Cumplido"),
                        ],
                        default="PENDIENTE",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "paciente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="objetivos",
                        to="dietetic.paciente",
                    ),
                ),
            ],
            options={
                "ordering": ["-fecha_inicio"],
            },
        ),
        migrations.CreateModel(
            name="PreferenciaAlimentaria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_preferencia",
                    models.CharField(
                        choices=[
                            ("VEGETARIANO", "Vegetariano"),
                            ("VEGANO", "Vegano"),
                            ("SIN_GLUTEN", "Sin gluten"),
                            ("SIN_LACTOSA", "Sin lactosa"),
                            ("ALERGIA_MARISCOS", "Alergia a mariscos"),
                            ("ALERGIA_NUECES", "Alergia a frutos secos"),
                            ("ALERGIA_HUEVOS", "Alergia a huevos"),
                            ("ALERGIA_SOJA", "Alergia a soja"),
                            ("LOW_CARB", "Dieta baja en carbohidratos"),
                            ("KETO", "Dieta cetogénica"),
                            ("MEDITERRANEA", "Dieta mediterránea"),
                            ("OTRO", "Otro"),
                        ],
                        max_length=30,
                    ),
                ),
                ("descripcion", models.TextField(blank=True, default="")),
                ("fecha_registro", models.DateTimeField(auto_now_add=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "paciente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="preferencias_alimentarias",
                        to="dietetic.paciente",
                    ),
                ),
            ],
            options={
                "ordering": ["-fecha_registro"],
            },
        ),
    ]
