# Generated by Django 6.0.5 on 2026-07-10 20:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dietetic", "0009_logropaciente_objetivopaciente_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="alimentoprogramado",
            name="calories",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name="alimentoprogramado",
            name="carbs",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name="alimentoprogramado",
            name="fat",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name="alimentoprogramado",
            name="protein",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="alimentoprogramado",
            name="categoria_alimento",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="alimentos_programados",
                to="dietetic.categoriaalimento",
            ),
        ),
        migrations.AlterField(
            model_name="alimentoprogramado",
            name="plan_nutricional",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="alimentos",
                to="dietetic.plannutricional",
            ),
        ),
        migrations.AlterField(
            model_name="alimentoprogramado",
            name="portion_grams",
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="sintomadiario",
            name="sintoma",
            field=models.CharField(
                choices=[
                    ("ANSIEDAD", "Ansiedad"),
                    ("CANSANCIO", "Cansancio"),
                    ("DOLOR_CABEZA", "Dolor de cabeza"),
                    ("BUENA_ENERGIA", "Buena energía"),
                    ("HAMBRE_EXCESIVA", "Hambre excesiva"),
                    ("SUEÑO_MALO", "Mal sueño"),
                    ("SUEÑO_BUENO", "Buen sueño"),
                    ("EXCELENTE", "Excelente"),
                    ("DIGESTION", "Problemas Digestivos"),
                ],
                max_length=20,
            ),
        ),
    ]
