# Generated by Django 6.0.5 on 2026-07-11 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "dietetic",
            "0010_alimentoprogramado_calories_alimentoprogramado_carbs_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="is_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="verification_code",
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
